---
frameworks:
  Apache PHP: apache_php
  Apache PHP 5/6: apache_php56
  Sinatra: sinatra
  Rails 4: rails4
  Rails 5: rails5
  OpenJDK 7: openjdk7
  OpenJDK 8: openjdk8
  OpenJDK 9: openjdk9
  Lua: lua
  Jetty: jetty
  Tomcat 7: tomcat7
  Tomcat 8: tomcat8
  Tomcat 9: tomcat9
  Python: python
  Base C: base_c
  NGINX: nginx
  RStudio: rstudio
  Meteor: meteor
  Node 6.9: node6.9
  Node 4.7: node4.7

script_languages:
  Javascript: javascript
  Lua: lua
  PHP: php
  Python: python
  R: r
  Shell: sh

database_seed_languages:
  Javascript: javascript
  Lua: lua
  NoSQL: nosql
  PHP: php
  Python: python
  R: r
  Shell: sh
  SQL: sql

required_module_types:
  Apache: apache
  Lua: lua
  PEAR: pear
  PECL: pecl
  PHP: php
  npm: npm